version: '3'

services:
  webapi:
    image: pomodoro-racer-be:latest
    container_name: pomodoro-racer-be
    build:
      context: ../PomodoroRacer.Backend/.
      dockerfile: Dockerfile-local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Abc.123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - AllowedCorsOrigins__Url=http://localhost:3000
    ports:
      - 5003:5001
      - 5004:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ~/.aspnet/https:/https:ro