FROM mcr.microsoft.com/dotnet/sdk:8.0.100-preview.7-jammy-arm64v8 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY src/ ./

RUN dotnet restore "./PomodoroRacer.Backend.sln"
RUN dotnet build "./PomodoroRacer.Backend.sln" -c Debug -o build
RUN dotnet publish "./PomodoroRacer.Backend.sln" -c Debug -o out

# Install dotnet debug tools
RUN dotnet tool install --tool-path /tools dotnet-trace \
 && dotnet tool install --tool-path /tools dotnet-counters \
 && dotnet tool install --tool-path /tools dotnet-dump \
 && dotnet tool install --tool-path /tools dotnet-gcdump

FROM mcr.microsoft.com/dotnet/aspnet:8.0.0-preview.7-jammy-chiseled-arm64v8

# Copy dotnet-tools
WORKDIR /tools
COPY --from=build-env /tools .

WORKDIR /app
COPY --from=build-env /app/out .

ENV ASPNETCORE_ENVIRONMENT Development

EXPOSE 5000
EXPOSE 5001
ENTRYPOINT ["dotnet", "PomodoroRacer.Backend.Startup.dll"]
